version: "3.8"
services:
  db:
    image: postgres:15
    container_name: burger-db
    environment:
      POSTGRES_DB: burgerbuilder
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sajaPassw0rd
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d burgerbuilder"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: burger-backend
    env_file:
      - ./environment.env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    container_name: burger-frontend
    depends_on:
      - backend
    ports:
      - "5173:80"

volumes:
  db_data:
